-- 系统标识相关模块
-- 参与者
create table BC_IDENTITY_ACTOR (
    ID integer NOT NULL auto_increment,
    UID varchar(20) NOT NULL COMMENT '全局标识',
    NAME varchar(255) COMMENT '名称',
    TYPE_ integer(1) NOT NULL COMMENT '类型：1-用户,2-岗位,3-部门,4-单位',
    EMAIL varchar(255) NOT NULL COMMENT '联系邮箱',
    PHONE varchar(255) NOT NULL COMMENT '联系电话',
    primary key (ID)
) COMMENT='事件参与者';

-- 参与者之间的关联关系
create table BC_IDENTITY_ACTOR_RELATION (
    TYPE_ integer(2) NOT NULL COMMENT '关联类型',
    MASTER_ID integer NOT NULL COMMENT '主控方ID',
   	FOLLOWER_ID integer NOT NULL COMMENT '从属方ID',
    ORDERNO varchar(5) COMMENT '从属方之间的排序号',
    primary key (MASTER_ID,FOLLOWER_ID,TYPE_)
) COMMENT='参与者之间的关联关系';
ALTER TABLE BC_IDENTITY_ACTOR_RELATION ADD CONSTRAINT FK_ARM_ACTOR FOREIGN KEY (MASTER_ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BC_IDENTITY_ACTOR_RELATION ADD CONSTRAINT FK_ARF_ACTOR FOREIGN KEY (FOLLOWER_ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID);

-- 用户
create table BC_IDENTITY_USER (
    ID integer NOT NULL,
    FIRST_NAME varchar(255) NOT NULL COMMENT '姓氏',
    LAST_NAME varchar(255) NOT NULL COMMENT '名字',
    SEX integer(1) NOT NULL COMMENT '性别：1-男,2-女',
    primary key (ID)
) COMMENT='系统用户';
ALTER TABLE BC_IDENTITY_USER ADD CONSTRAINT FK_USER_ACTOR FOREIGN KEY (ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID) ON DELETE CASCADE ON UPDATE RESTRICT;

-- 组织：岗位、部门、单位
create table BC_IDENTITY_ORGANIZER (
    ID integer NOT NULL,
    BELONG integer COMMENT '所隶属的组织',
    primary key (ID)
) COMMENT='组织：岗位、部门、单位';
ALTER TABLE BC_IDENTITY_ORGANIZER ADD CONSTRAINT FK_ORGANIZER_ACTOR FOREIGN KEY (ID) 
	REFERENCES BC_IDENTITY_ACTOR (ID) ON DELETE CASCADE ON UPDATE RESTRICT;


-- 系统安全相关模块
-- 模块
create table BC_SECURITY_MODULE (
    ID integer NOT NULL auto_increment,
    BELONG integer COMMENT '所隶属的模块',
    TYPE_ integer(1) NOT NULL COMMENT '类型：1-文件夹,2-内部链接,3-外部链接',
    CODE varchar(255) NOT NULL COMMENT '编码',
    LABEL varchar(255) NOT NULL COMMENT '名称',
    URL varchar(255) COMMENT '地址',
    OPTIONS varchar(255) COMMENT '模块的初始化参数',
    primary key (ID)
) COMMENT='系统模块';

-- 角色
create table BC_SECURITY_ROLE (
    ID integer NOT NULL auto_increment,
    ORG_ID integer COMMENT '所隶属的组织',
   	TYPE_ integer(1) NOT NULL COMMENT '类型',
    CODE varchar(255) NOT NULL COMMENT '编码',
    LABEL varchar(255) NOT NULL COMMENT '名称',
    primary key (ID)
) COMMENT='系统角色';
ALTER TABLE BC_SECURITY_ROLE ADD CONSTRAINT FK_ROLE_ORGANIZER FOREIGN KEY (ORG_ID) 
	REFERENCES BC_IDENTITY_ORGANIZER (ID);

-- 角色与权限的关联
create table BC_SECURITY_ROLE_MODULE (
    RID integer NOT NULL COMMENT '角色ID',
    MID integer NOT NULL COMMENT '模块ID',
    primary key (RID,MID)
) COMMENT='角色与权限的关联';
ALTER TABLE BC_SECURITY_ROLE_MODULE ADD CONSTRAINT FK_RM_ROLE FOREIGN KEY (RID) 
	REFERENCES BC_SECURITY_ROLE (ID);
ALTER TABLE BC_SECURITY_ROLE_MODULE ADD CONSTRAINT FK_RM_MODULE FOREIGN KEY (MID) 
	REFERENCES BC_SECURITY_MODULE (ID);
